version: "3.8"

services:

  fraud-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"

  simulator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python scripts/transaction_simulator.py
    depends_on:
      - fraud-api

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: streamlit run monitoring/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - fraud-api